import { useState, useEffect } from "react";
import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";
import { useNavigate } from "react-router-dom";
import axios from "axios";
import { LogOut, CheckCircle2, XCircle, Clock, Search, Filter, Calendar } from "lucide-react";

export default function StaffDashboard() {
  const [staff, setStaff] = useState(null);
  const [students, setStudents] = useState([]);
  const [attendance, setAttendance] = useState({});
  const [selectedDate, setSelectedDate] = useState(new Date().toISOString().split('T')[0]);
  const [searchTerm, setSearchTerm] = useState("");
  const [loading, setLoading] = useState(true);
  const navigate = useNavigate();

  const API_URL = "/api";

  useEffect(() => {
    const fetchData = async () => {
      try {
        const staffRes = await axios.get(`${API_URL}/staff/profile`, { withCredentials: true });
        setStaff(staffRes.data);
        
        const studentsRes = await axios.get(`${API_URL}/students/admin/list`, { withCredentials: true });
        setStudents(studentsRes.data);

        const attRes = await axios.get(`${API_URL}/staff/attendance/${selectedDate}`, { withCredentials: true });
        const attMap = {};
        attRes.data.forEach(a => attMap[a.student_id] = a.status);
        setAttendance(attMap);
      } catch (err) {
        navigate("/staff/login");
      } finally {
        setLoading(false);
      }
    };
    fetchData();
  }, [selectedDate, navigate]);

  const markAttendance = async (studentId, status) => {
    try {
      await axios.post(`${API_URL}/staff/attendance`, {
        student_id: studentId,
        status,
        date: selectedDate
      }, { withCredentials: true });
      setAttendance({ ...attendance, [studentId]: status });
    } catch (err) {
      alert("Failed to mark attendance");
    }
  };

  const downloadPDFReport = async () => {
    try {
      const res = await axios.get(`${API_URL}/staff/students-summary`, { withCredentials: true });
      const data = res.data;



      const doc = new jsPDF("p", "pt", "a4");

      // Header Bar (Green Accent)
      doc.setFillColor(29, 74, 58);
      doc.rect(0, 0, 595.28, 80, "F");

      // Header Text (White)
      doc.setTextColor(255, 255, 255);
      doc.setFont("helvetica", "bold");
      doc.setFontSize(14);
      doc.text("SRI SAI INSTITUTE OF AGRICULTURAL SCIENCES", 40, 36);

      doc.setFont("helvetica", "normal");
      doc.setFontSize(8);
      doc.text("FACULTY PORTAL | STUDENT ATTENDANCE REPORT & ANALYTICS", 40, 52);

      // Metadata Info Box
      doc.setFillColor(248, 250, 252);
      doc.rect(40, 100, 515.28, 45, "F");

      doc.setTextColor(51, 65, 85);
      doc.setFontSize(8);
      doc.setFont("helvetica", "bold");
      doc.text("GENERATED BY:", 55, 118);
      doc.setFont("helvetica", "normal");
      doc.text(String(staff?.name || 'FACULTY').toUpperCase(), 135, 118);

      doc.setFont("helvetica", "bold");
      doc.text("DEPARTMENT:", 55, 132);
      doc.setFont("helvetica", "normal");
      doc.text(String(staff?.department || 'AGRICULTURE').toUpperCase(), 135, 132);

      doc.setFont("helvetica", "bold");
      doc.text("REPORT DATE:", 360, 118);
      doc.setFont("helvetica", "normal");
      const todayDate = new Date().toLocaleDateString('en-IN', {
        day: 'numeric', month: 'short', year: 'numeric', hour: '2-digit', minute: '2-digit'
      });
      doc.text(todayDate, 435, 118);

      doc.setFont("helvetica", "bold");
      doc.text("TOTAL ENROLLED:", 360, 132);
      doc.setFont("helvetica", "normal");
      doc.text(`${data.length} Students`, 435, 132);

      const tableHeaders = [
        ["#", "Student Name", "Roll Number", "Working Days", "Days Present", "Days Absent", "Attendance %"]
      ];

      const tableRows = data.map((student, idx) => [
        idx + 1,
        student.student_name.toUpperCase(),
        student.roll_no || 'N/A',
        student.total_days,
        student.present_days,
        student.absent_days,
        `${student.percentage}%`
      ]);

      autoTable(doc, {
        head: tableHeaders,
        body: tableRows,
        startY: 165,
        margin: { left: 40, right: 40 },
        theme: 'striped',
        headStyles: {
          fillColor: [29, 74, 58],
          textColor: [255, 255, 255],
          fontStyle: 'bold',
          fontSize: 9,
          halign: 'center'
        },
        columnStyles: {
          0: { halign: 'center', cellWidth: 30 },
          1: { fontStyle: 'bold', fontSize: 9 },
          2: { halign: 'center', fontSize: 9 },
          3: { halign: 'center', fontSize: 9 },
          4: { halign: 'center', fontSize: 9 },
          5: { halign: 'center', fontSize: 9 },
          6: { halign: 'center', fontStyle: 'bold', fontSize: 9 }
        },
        bodyStyles: {
          fontSize: 9,
          textColor: [30, 41, 59]
        },
        alternateRowStyles: {
          fillColor: [248, 250, 252]
        },
        didParseCell: function(dataCell) {
          if (dataCell.column.index === 6 && dataCell.section === 'body') {
            const pct = parseFloat(dataCell.cell.raw);
            if (pct < 75.0) {
              dataCell.cell.styles.textColor = [239, 68, 68];
              dataCell.cell.styles.fontStyle = 'bold';
            } else {
              dataCell.cell.styles.textColor = [22, 163, 74];
              dataCell.cell.styles.fontStyle = 'bold';
            }
          }
        }
      });

      const totalPages = doc.internal.getNumberOfPages();
      for (let i = 1; i <= totalPages; i++) {
        doc.setPage(i);
        doc.setFontSize(8);
        doc.setTextColor(148, 163, 184);
        doc.setFont("helvetica", "normal");
        doc.text(`Page ${i} of ${totalPages}`, 297.64, 820, { align: 'center' });
        doc.text("Official Sri Sai Portal Verification Stamp", 555.28, 820, { align: 'right' });
      }

      doc.save(`Student_Attendance_Report_${selectedDate}.pdf`);

    } catch (err) {
      console.error("PDF generation error:", err);
      alert("Failed to generate and download PDF report. Please try again.");
    }
  };

  const filteredStudents = students.filter(s => 
    s.student_name.toLowerCase().includes(searchTerm.toLowerCase()) || 
    s.roll_no?.toLowerCase().includes(searchTerm.toLowerCase())
  );

  if (loading) return <div className="min-h-screen flex items-center justify-center font-black text-blue animate-pulse">LOADING DASHBOARD...</div>;

  return (
    <div className="min-h-screen bg-[#f8fafc] flex flex-col">
      {/* Header */}
      <header className="bg-white border-b border-gray-100 px-8 py-5 flex items-center justify-between sticky top-0 z-50 shadow-sm">
        <div className="flex items-center gap-4">
           <div className="h-11 w-11 bg-white rounded-2xl p-1 flex items-center justify-center border border-gray-100 shadow-md shrink-0">
              <img src="/logo.png" alt="Sri Sai Agricultural College Logo" className="h-full w-full object-contain" />
           </div>
           <div>
              <h1 className="text-xl font-black text-ink uppercase tracking-tight">Attendance Register</h1>
              <p className="text-[10px] text-muted font-bold tracking-widest uppercase">Sri Sai Staff Portal</p>
           </div>
        </div>

        <div className="flex items-center gap-6">
           <div className="hidden md:flex flex-col text-right">
              <span className="font-bold text-sm text-ink">{staff?.name}</span>
              <span className="text-[10px] font-black text-blue/60 uppercase tracking-widest">{staff?.department}</span>
           </div>
           <button 
             onClick={() => { document.cookie = "staffToken=; max-age=0; path=/;"; navigate("/staff/login"); }}
             className="p-3 bg-red-50 text-red-500 rounded-xl hover:bg-red-500 hover:text-white transition-all shadow-lg shadow-red-500/5"
           >
              <LogOut size={18} />
           </button>
        </div>
      </header>

      <main className="p-8 space-y-10">
         {/* Controls */}
         <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
            <div className="lg:col-span-2 bg-white p-6 rounded-[2.5rem] shadow-xl shadow-blue/5 border border-gray-100 flex items-center gap-4">
               <div className="h-10 w-10 bg-gray-50 rounded-xl flex items-center justify-center text-muted">
                  <Search size={20} />
               </div>
               <input 
                 placeholder="Search student by name or roll number..." 
                 value={searchTerm}
                 onChange={(e) => setSearchTerm(e.target.value)}
                 className="flex-grow bg-transparent border-none outline-none font-bold text-ink"
               />
            </div>
            <div className="bg-white p-6 rounded-[2.5rem] shadow-xl shadow-blue/5 border border-gray-100 flex items-center justify-between px-10">
               <span className="text-[10px] font-black text-muted uppercase tracking-widest">Select Date</span>
               <input 
                 type="date" 
                 value={selectedDate}
                 onChange={(e) => setSelectedDate(e.target.value)}
                 className="bg-sky/30 border-none outline-none font-black text-blue px-4 py-2 rounded-xl text-xs uppercase"
               />
            </div>
         </div>

         {/* Student List */}
         <div className="bg-white rounded-[3rem] shadow-2xl shadow-blue/5 border border-gray-100 overflow-hidden">
            <div className="p-8 border-b border-gray-50 flex flex-col sm:flex-row sm:items-center justify-between gap-4">
                <div className="flex items-center gap-4">
                   <h3 className="font-black text-ink text-sm uppercase tracking-widest">Enrollment List ({filteredStudents.length})</h3>
                   <button 
                     onClick={downloadPDFReport}
                     className="px-4 py-2 bg-blue hover:bg-blue/90 text-white rounded-xl text-[10px] font-black uppercase tracking-widest transition-all shadow-md shadow-blue/10 flex items-center gap-2 hover:scale-[1.02] active:scale-[0.98]"
                   >
                      <svg className="w-3.5 h-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                         <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2.5" d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4"></path>
                      </svg>
                      Download PDF Report
                   </button>
                </div>
               <div className="flex items-center gap-4">
                  <div className="flex items-center gap-2">
                     <div className="h-3 w-3 bg-blue rounded-full"></div>
                     <span className="text-[10px] font-bold text-muted uppercase">Present</span>
                  </div>
                  <div className="flex items-center gap-2">
                     <div className="h-3 w-3 bg-orange rounded-full"></div>
                     <span className="text-[10px] font-bold text-muted uppercase">Absent</span>
                  </div>
               </div>
            </div>

            <div className="overflow-x-auto">
               <table className="w-full">
                  <thead>
                     <tr className="bg-gray-50">
                        <th className="px-10 py-5 text-left text-[9px] font-black text-gray-400 uppercase tracking-widest">Student Info</th>
                        <th className="px-10 py-5 text-center text-[9px] font-black text-gray-400 uppercase tracking-widest">Status</th>
                        <th className="px-10 py-5 text-right text-[9px] font-black text-gray-400 uppercase tracking-widest">Mark Attendance</th>
                     </tr>
                  </thead>
                  <tbody className="divide-y divide-gray-50">
                     {filteredStudents.map(student => (
                        <tr key={student.id} className="hover:bg-gray-50/50 transition-colors">
                           <td className="px-10 py-6">
                              <div className="flex items-center gap-4">
                                 <div className="h-12 w-12 rounded-2xl bg-sky flex items-center justify-center text-blue font-black shadow-inner overflow-hidden">
                                    {student.photo ? <img src={student.photo} className="h-full w-full object-cover" /> : student.student_name[0]}
                                 </div>
                                 <div className="flex flex-col">
                                    <span className="font-black text-ink text-sm uppercase">{student.student_name}</span>
                                    <span className="text-[10px] font-bold text-muted uppercase tracking-widest">{student.roll_no}</span>
                                 </div>
                              </div>
                           </td>
                           <td className="px-10 py-6 text-center">
                              {attendance[student.id] ? (
                                 <span className={`px-4 py-2 rounded-xl text-[10px] font-black uppercase tracking-widest ${attendance[student.id].toLowerCase() === 'present' ? 'bg-sky2 text-blue border border-blue/20' : 'bg-red-50 text-orange border border-orange/20'}`}>
                                    {attendance[student.id]}
                                 </span>
                              ) : (
                                 <span className="text-[9px] font-bold text-gray-300 uppercase tracking-widest italic">Not Marked</span>
                              )}
                           </td>
                           <td className="px-10 py-6">
                              <div className="flex items-center justify-end gap-3">
                                 <button 
                                   onClick={() => markAttendance(student.id, 'Present')}
                                   className={`p-3 rounded-xl border transition-all ${
                                     attendance[student.id]?.toLowerCase() === 'present' 
                                       ? 'bg-blue text-white border-blue shadow-lg shadow-blue/30' 
                                       : 'bg-sky text-blue border-sky2 hover:bg-blue hover:text-white hover:border-blue shadow-sm'
                                   }`}
                                   title="Mark Present"
                                 >
                                    <CheckCircle2 size={22} strokeWidth={2.5} />
                                 </button>
                                 <button 
                                   onClick={() => markAttendance(student.id, 'Absent')}
                                   className={`p-3 rounded-xl border transition-all ${
                                     attendance[student.id]?.toLowerCase() === 'absent' 
                                       ? 'bg-orange text-white border-orange shadow-lg shadow-orange/30' 
                                       : 'bg-red-50 text-orange border-red-100 hover:bg-orange hover:text-white hover:border-orange shadow-sm'
                                   }`}
                                   title="Mark Absent"
                                 >
                                    <XCircle size={22} strokeWidth={2.5} />
                                 </button>
                              </div>
                           </td>
                        </tr>
                     ))}
                  </tbody>
               </table>
            </div>
         </div>
      </main>
    </div>
  );
}
